###
GET http://localhost:4000/buys/get/all

###
GET http://localhost:4000/marks/get/all


///////////////////////////////

###
GET http://localhost:4000/locals/get/all

###
PUT http://localhost:4000/locals/delete/cb99db88-30b4-4a57-b153-ac798a8ff764


///////////////////////////////

###
GET http://localhost:4000/buys/get/by-product/e2fee4ba-d4c1-4605-b794-cc428fd47b4e

###
GET http://localhost:4000/locals/new/validate/description/arroz

###
GET http://localhost:4000/products/new/validate/description/as

###
GET https://172.17.10.134:4000/products/new/validate/description/s

###
GET http://localhost:4000/products/get/id/e2fee4ba-d4c1-4605-b794-cc428fd47b4e

###
PUT http://localhost:4000/products/delete/c36864ab-f03a-4e79-97f8-57a4382abf7b

###
GET http://localhost:4000/products/get/?search=ice

/////////////////

###
GET http://localhost:4000/products/get/id/334ee704-b398-49da-913a-c047bf0002b0

###
GET http://localhost:4000/products/get/all


// UPDATE
###
PUT http://localhost:4000/products/update/id/334ee704-b398-49da-913a-c047bf0002b0
Content-Type: application/json

{
	"markId": "08309c42-d349-4e1b-af81-b11919b048ad"
}

/////////////////

###
GET http://localhost:4000/products/get/mark/83562c16-2781-4256-becf-4cb18550f360

###
GET http://localhost:4000/buys/get/07e5ac6d-029a-4708-a222-69e9ea1e073cx

###
GET http://localhost:4000/buys/1f18bb1a-e263-4c39-9c63-b1e5a5a93901

###
PUT http://localhost:4000/locals/delete/69db36cb-c507-401a-b48d-a3262493f460
Content-Type: application/json

{
	"description": "açougue"
}

###
POST http://localhost:4000/marks/new
Content-Type: application/json

{
	"description": "perdigão"
}

###
POST http://localhost:4000/locals/new
Content-Type: application/json

{
	"description": "padaria"
}

###
POST http://localhost:4000/products/new
Content-Type: application/json

{
	"description": "ardr3oz",
	"codeBar": "edqdwe",
	"lastPrice": 28.3,
	"markId": "ea9669b2-6d04-42d1-b0fc-d2893bfde80c"
}


###
POST http://localhost:4000/buys/new
Content-Type: application/json

{
	"localId": "950283af-2e94-4c98-bcc0-53429cc1f2f5",
  "products": [
    {
      "productId": "f8155d94-fe5a-4f65-99b6-92508b053bc0",
      "amount": 1.4,
      "unitPrice": 561.46
    }
  ]
}



###
POST http://localhost:4000/buys/new
Content-Type: application/json

{
  "products": [
    {
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
	    {
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    }
  ]
}