GET http://localhost:4000/buys/get/all

###
GET http://localhost:4000/marks/get/all

###
GET http://localhost:4000/locals/get/all

###
GET http://localhost:4000/locals/new/validate/description/arroz

###
GET http://localhost:4000/products/new/validate/description/as

###
GET https://172.17.10.134:4000/products/new/validate/description/s

###
GET http://localhost:4000/products/get/all

###
GET http://localhost:4000/products/get/?search=ice

###
GET http://localhost:4000/products/get/lojinha

###
GET http://localhost:4000/products/get/mark/83562c16-2781-4256-becf-4cb18550f360

###
GET http://localhost:4000/buys/get/07e5ac6d-029a-4708-a222-69e9ea1e073c

###
PUT http://localhost:4000/products/delete/32238ca5-24e8-4261-820c-088d8f274eb3

###
GET http://localhost:4000/buys/1f18bb1a-e263-4c39-9c63-b1e5a5a93901

###
PUT http://localhost:4000/locals/delete/69db36cb-c507-401a-b48d-a3262493f460
Content-Type: application/json

{
	"description": "açougue"
}

###
POST http://localhost:4000/marks/new
Content-Type: application/json

{
	"description": "perdigão"
}

###
POST http://localhost:4000/locals/new
Content-Type: application/json

{
	"description": "padaria"
}

###
POST http://localhost:4000/products/new
Content-Type: application/json

{
	"description": "ardr3oz",
	"codeBar": "edqdwe",
	"lastPrice": 28.3,
	"markId": "ea9669b2-6d04-42d1-b0fc-d2893bfde80c"
}

###
PUT http://localhost:4000/products/update/ca3714e3-2da4-4588-8dd2-583485b5c767
Content-Type: application/json

{
	"description": "arroz"
}


###
POST http://localhost:4000/buys/new
Content-Type: application/json

{
	"localId": "950283af-2e94-4c98-bcc0-53429cc1f2f5",
  "products": [
    {
      "productId": "f8155d94-fe5a-4f65-99b6-92508b053bc0",
      "amount": 14.4,
      "unitPrice": 354.46
    },
    {
      "productId": "13b280da-5c2c-4989-bae9-2e74d2983f7a",
      "amount": 23,
      "unitPrice": 3.99
    },
		    {
      "productId": "938a96bc-75a9-47cd-99fa-d2ae26d6f545",
      "amount": 94,
      "unitPrice": 43.43
    }
  ]
}



###
POST http://localhost:4000/buys/new
Content-Type: application/json

{
  "products": [
    {
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
	    {
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    },
		{
      "productId": "f87452eb-51a2-43c2-8496-cafc4786a2c1",
      "amount": 33.88,
      "unitPrice": 50.08
    }
  ]
}